# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17c5372d35d826d23f312ab3336033f3d1240d2ada6f6e32c908834cfe8e2da6ca5c6e840dcfa5996cd0b07a0ee4e428aa420f2f20072652a1d8205bee22695e

test:
  secret_key_base: 0403396d6d927e34dde59ef19f8e808a11532887410384d7cd99749f600429dcad5764751591925a4552118175ee9e2c0788dacfda2f70fb340e14c92ed79249

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
